@startuml
!include <C4/C4_Container>

title Диаграмма контейнеров для системы депонирования научных работ

Person(admin, "Администратор", "Администратор системы депонирования")
Person(user, "Пользователь", "Исследователь депонированных работ")

System_Boundary(system, "Система депонирования") {

    Container(web_app, "Веб-интерфейс", "Основной интерфейс пользователей")

    Container(api_gateway, "API Gateway", "Единная точка входа в приложение")

    Container(auth_service, "Сервис аутентификации/авторизации")
    Container(analytic_service, "Сервис анализа депонированных работ")
    Container(deposition_service, "Сервис депонированных работ")

    ContainerDb(blockchain, "Blockchain", "Хранит данные депонирования")
    ContainerDb(dfs, "Распределенная файловая система", "Хранит объекты интеллектуальной собственноси")
}

Container_Ext(organization_service, "Сервис организации")

Rel(organization_service, api_gateway, "Отправляет запросы")

Rel(web_app, api_gateway, "Отправляет запросы")

Rel(admin, web_app, "Использует для администрирования")
Rel(user, web_app, "Использует для поиска работ")

Rel(api_gateway, auth_service, "Отправляет запросы")
Rel(api_gateway, analytic_service, "Отправляет запросы")
Rel(api_gateway, deposition_service, "Отправляет запросы")

Rel(deposition_service, blockchain, "Сохраняет данные")
Rel(deposition_service, dfs, "Сохраняет данные")

@enduml
