@startuml
hide methods
hide empty fields
hide circle
skinparam linetype ortho

title Logical Off-chain Data Model (DFS) — PREMIS-compatible

package ObjectFrame <<Frame>> {

  entity ObjectMetadata {
    id : String
    version : Long
    category : ObjectCategory
    originalName : String
    characteristics : Characteristics[]
    storage : Storage
    identifiers : Identifier[]
  }

  entity Characteristics {
    size : Long
    fixity : FixityBlock[]
    format : FormatBlock[]
  }

  entity FixityBlock {
    algorithm : String
    digest : String
  }

  entity FormatBlock {
    formatDesignation : FormatDesignation
  }

  entity FormatDesignation {
    name : String
    version : String
  }

  entity Storage {
    contentLocation: ContentLocation
  }

  entity ContentLocation {
    contentLocationType : String
    contentLocationValue : String
  }

  entity DescriptiveMetadata {
    id: String
    payload : JSON
  }

  entity ObjectIdentifier {
    type : String
    value : String
  }
}

package EventFrame <<Frame>> {

  entity Event {
    id : String
    type : EventType
    dateTime : DateTime
    outcome : EventOutcomeInformation[]
    detail : EventDetailInformation[]
    identifiers : Identifier[]
    eventObjectRelations : EventObjectRelation[]
  }

  enum EventType {
    ACCESSION
    CREATION
    DEACCESSION
    DELETION
    METADATA MODIFICATION
    MIGRATION
    ...
  }

  entity EventDetailInformation {
    detail : String
  }

  entity EventOutcomeInformation {
    outcome : EventOutcome
    outcomeDetail : EventOutcomeInformationDetail
  }

  enum EventOutcome {
    SUCCESS
    FAILURE
  }

  entity EventOutcomeInformationDetail {
    eventOutcomeDetailNote : String
  }

  entity EventAgentLink {
    agentId : String
    role : EventAgentLinkRole
  }

  enum EventAgentLinkRole {
    AUTHORIZER
    EXECUTING_PROGRAM
    IMPLEMENTER
    VALIDATOR
  }

  entity EventObjectRelation {
    objectId : String
    role : EventObjectRelationRole
  }

  enum EventObjectRelationRole {
    OUTCOME
    SOURCE
  }

  entity EventIdentifier {
    type : String
    value : String
  }
}

package AgentFrame <<Frame>> {

  entity AgentMetadata {
    id : String
    version : Long
    name : String
    type : AgentType
    identifiers : Identifier[]
  }

  enum AgentType {
    HARDWARE
    ORGANIZATION
    PERSON
    SOFTWARE
  }

  entity AgentIdentifier {
    type : String
    value : String
  }
}

package "RightsStatementFrame" <<Frame>> {

  entity RightsStatementMetadata {
    id : String
    rightsBasis : RightsBasis
    copyrightInformation : CopyrightInformation[]
    licenseInformation : LicenseInformation[]
    statuteInformation : StatuteInformation[]
    otherRightsInformation : OtherRightsInformation[]
    rightsGranted : RightsGranted[]
    identifiers : Identifier[]
  }

  enum RightsBasis {
    COPYRIGHT
    LICENSE
    STATUTE
    OTHER
  }

  entity CopyrightInformation {
    copyrightStatus : String
    copyrightJurisdiction : String
    copyrightStatusDeterminationDate : Date
    copyrightNote : String[]
    documentationIdentifiers : DocumentationIdentifier[]
    applicableDates : ApplicableDates
  }

  entity LicenseInformation {
    documentationIdentifiers : DocumentationIdentifier[]
    licenseTerms : String
    licenseNote : String[]
    applicableDates : ApplicableDates
  }

  entity StatuteInformation {
    statuteJurisdiction : String
    statuteCitation : String
    statuteInformationDeterminationDate : Date
    statuteNote : String[]
    documentationIdentifiers : DocumentationIdentifier[]
    applicableDates : ApplicableDates
  }

  entity OtherRightsInformation {
    documentationIdentifiers : DocumentationIdentifier[]
    otherRightsBasis : String
    applicableDates : ApplicableDates
    otherRightsNote : String[]
  }

  entity RightsGranted {
    act : String
    restriction : String[]
    termOfGrant : ApplicableDates
    termOfRestriction : ApplicableDates
    rightsGrantedNote : String[]
  }

  entity DocumentationIdentifier {
    type : String
    value : String
    role : String
  }

  entity ApplicableDates {
    startDate : Date
    endDate : Date
  }

  entity RightsStatementIdentifier {
    type : String
    value : String
  }
}

ObjectMetadata ||-o{ ObjectIdentifier
ObjectMetadata ||--|{ Characteristics
ObjectMetadata ||--|{ Storage

Characteristics ||--|{ FixityBlock
Characteristics ||--|{ FormatBlock

FormatBlock ||-|| FormatDesignation

Storage ||--|| ContentLocation



Event ||--o{ EventDetailInformation
Event ||--o{ EventOutcomeInformation
Event ||-o{ EventObjectRelation
Event ||-o{ EventAgentLink
Event ...> EventType
Event ||-o{ EventIdentifier

EventOutcomeInformation ..> EventOutcome
EventOutcomeInformation ||--o{ EventOutcomeInformationDetail

EventObjectRelation ...> EventObjectRelationRole

EventAgentLink ...> EventAgentLinkRole 



AgentMetadata ||--o{ AgentIdentifier
AgentMetadata ..> AgentType





RightsStatementMetadata ||--o{ RightsStatementIdentifier

RightsStatementMetadata .> RightsBasis

RightsStatementMetadata ||--o{ CopyrightInformation
CopyrightInformation ||--o{ DocumentationIdentifier
CopyrightInformation ||--|| ApplicableDates

RightsStatementMetadata ||--o{ LicenseInformation
LicenseInformation ||--o{ DocumentationIdentifier
LicenseInformation ||--|| ApplicableDates

RightsStatementMetadata ||---o{ StatuteInformation
StatuteInformation ||--o{ DocumentationIdentifier
StatuteInformation ||--|| ApplicableDates

RightsStatementMetadata ||--o{ OtherRightsInformation
OtherRightsInformation ||--o{ DocumentationIdentifier
OtherRightsInformation ||--|| ApplicableDates

RightsStatementMetadata ||--o{ RightsGranted
RightsGranted ||--|| ApplicableDates : termOfGrant
RightsGranted ||--|| ApplicableDates : termOfRestriction


FixityBlock -[hidden]down> EventFrame
AgentFrame -[hidden]down> EventFrame

@enduml
