@startuml
left to right direction
skinparam linetype ortho

hide methods
hide empty fields

abstract class DescriptionMetadata {
}

class PremisEntity {
}

class DublinCoreMetadata {
}

class DataCiteMetadata {
}

DescriptionMetadata ||--|| PremisEntity
DublinCoreMetadata --|> DescriptionMetadata
DataCiteMetadata --|> DescriptionMetadata

@enduml
