@startuml

left to right direction

title Диаграмма вариантов использования\nсистемы депонирования научно-исследовательских работ

actor "Исследователь" as Researcher
actor "Создатель ИС" as Creator
actor "Администратор системы" as OrgAdmin

rectangle "Система Депонирования" {

    (Депонировать объект ИС) as UC_DepositObject
    (Просматривать депонированные \n объекты) as UC_ViewDepositedObjects
    (Запросить подтверждение\nфакта депонирования) as UC_RequestDepositConfirmation

    together {
        (Загрузить файлы) as UC_UploadFiles
        (Заполнить метаданные) as UC_FillMetadata
    }

    UC_DepositObject ..> UC_UploadFiles : includes
    UC_DepositObject ..> UC_FillMetadata : includes

    (Управлять способами \n аутентификации и авторизации) as UC_ManageAuthMethods
    (Управлять ролевой моделью) as UC_ManageRoles
    (Контролировать работу системы) as UC_MonitorSystem

    together {
        (Просматривать публичную статистику) as UC_ViewPublicStatistics
        (Использовать фильтры поиска) as UC_UseSearchFilters
        (Просматривать контент объекта) as UC_ViewObjectContent
    }

    UC_ViewDepositedObjects <.. UC_UseSearchFilters : extends
    UC_ViewDepositedObjects <.. UC_ViewObjectContent : extends
    UC_ViewDepositedObjects <.. UC_ViewPublicStatistics : extends

    (Просматривать личную статистику) as UC_ViewPersonalStatistics

    together {
        (Просматривать системные метрики) as UC_ViewSystemMetrics
        (Просматривать бизнес метрики) as UC_ViewBusinessMetrics
    }

    UC_MonitorSystem <.. UC_ViewSystemMetrics : extends
    UC_MonitorSystem <.. UC_ViewBusinessMetrics : extends

    together {
        (Управлять схемами \n метаданных объектов) as UC_ManageMetadataSchemas
        (Обновлять конфигурацию процесса) as UC_UpdateProcessConfiguration
        (Интегрировать внешние сервисы) as UC_IntegrateExternalServices
    }
    (Управлять конфигурацией процесса депонирования) as UC_ManageDepositionProcess
    
    UC_ManageDepositionProcess <.. UC_ManageMetadataSchemas : extends
    UC_ManageDepositionProcess <.. UC_UpdateProcessConfiguration : extends
    UC_ManageDepositionProcess <.. UC_IntegrateExternalServices : extends
}

Researcher -- UC_ViewDepositedObjects

Creator -- UC_DepositObject
Creator -- UC_RequestDepositConfirmation
Creator -- UC_ViewPersonalStatistics

OrgAdmin -- UC_ManageAuthMethods
OrgAdmin -- UC_ManageRoles
OrgAdmin -- UC_MonitorSystem
OrgAdmin -- UC_ManageDepositionProcess

@enduml
