@startuml

left to right direction

title Диаграмма вариантов использования\nСистемы Депонирования Интеллектуальной Собственности

actor "Какой-то пользователь" as SomeUser
actor "Создатель ИС" as Creator
actor "Администратор системы" as OrgAdmin
actor "Система организации" as ExternalServices

rectangle "Система Депонирования" {
    (Депонировать объект) as UC1
    (Управлять метаданными) as UC2
    (Просматривать депонированные объекты) as UC3
    (Запросить подтверждение\nфакта депонирования) as UC4
    (Администрировать систему) as UC7


    together {
        (Загрузить файлы) as UC8
        (Заполнить метаданные) as UC10
    }

    UC1 ..> UC8 : includes
    UC1 ..> UC10 : includes

    together {
        (Управлять пользователями) as UC11
        (Настраивать ролевую модель) as UC12
        (Мониторинг работы) as UC13
    }

    UC7 <.. UC11 : extends
    UC7 <.. UC12 : extends
    UC7 <.. UC13 : extends


    together {
        (Просмотр публичной статистики) as UC16
        (Использовать фильтры) as UC14
        (Просматривать контент работы) as UC15
    }
    UC3 <.. UC14 : extends
    UC3 <.. UC15 : extends
    UC3 <.. UC16 : extends

    (Просмотр системной статистики) as UC18

    (Просматривать личную статистику) as UC17
    (Управлять метаданными) as UC21
    together {
    }
}

SomeUser -- UC3
SomeUser <|-- Creator

Creator -- UC1
Creator -- UC4
Creator -- UC17
Creator -- UC21

OrgAdmin -- UC2
OrgAdmin -- UC7
OrgAdmin -- UC18

@enduml